# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f930591a86f340895428f22d532783b56cbaf8112d0969987fae14967ce8738098c3142ffc84a85870b297276debd6fc3b988fd07d20ad1813acfe28ac23a43

test:
  secret_key_base: e651f4b8bbfd5868c4bb2a9ef17d2c49c6d825ec0c1103921c758941e6331c0ee63532504322a952d0307a00bff0305a0806d1196c77d097688f02d3d42c046a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
